language: python
env:  # These should match the tox env list
 - TOXENV=py26
 - TOXENV=py27
 - TOXENV=py33
 - TOXENV=py34
before_script:
 - pip install future
 - mysql -e 'create database mysqldb_test charset utf8;'
script: TESTDB=travis.cnf tox
