language: python
env:  # These should match the tox env list
 - TOXENV=py26
 - TOXENV=py27
 - TOXENV=py33
 - TOXENV=py34
 - TOXENV=pypy
 - TOXENV=pyhack
install:
 - pip install tox
before_script:
 - mysql -e 'create database mysqldb_test charset utf8;'
script: TESTDB=travis.cnf tox
matrix:
  allow_failures:
    - env: "TOXENV=pypy"
